"""Source selection, path resolution and input seeding.

These three decide what a node reads and writes. Every production failure this
pipeline's design notes describe was one of them going wrong quietly.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from pipeline.io import SourceSpec, SourcesConfig
from pipeline.paths import (
    DEFAULT_DATA_ROOT,
    PROJECT_ROOT,
    SOURCES_YAML,
    resolve_input_root,
    resolve_output_root,
)
from pipeline.runner import seed_from_input


# --- the pipeline YAMLs ---------------------------------------------------

PIPELINE_YAMLS = ("fasttrack_pipeline.yaml", "fasttrack_pipeline_inline.yaml")

# The model vFolder is account-scoped, so both files ship a name the reader is
# told to replace. A real folder name reaching main means somebody's own cluster
# was committed, and the file stops working for everybody else.
PLACEHOLDER_VFOLDER = "your_model_folder"


def load_pipeline(name: str) -> dict:
    import yaml

    return yaml.safe_load((PROJECT_ROOT / name).read_text())


@pytest.mark.parametrize("name", PIPELINE_YAMLS)
def test_every_setting_can_be_typed_into_the_pipeline_yaml(name):
    """Both YAMLs advertise themselves as the place to configure everything.

    If a new Settings field is added without a line in the `envs` block, that
    claim quietly stops being true and the only way to set it becomes a .env
    file the README calls optional.
    """
    from docs_rag.settings import Settings

    envs = load_pipeline(name)["environment"]["envs"]
    missing = {field.upper() for field in Settings.model_fields} - set(envs)
    assert not missing, f"{name}: settings with no line in the envs block: {sorted(missing)}"


@pytest.mark.parametrize("name", PIPELINE_YAMLS)
def test_no_credential_is_ever_committed(name):
    """A published example must not carry a usable secret.

    An unresolved ${{ secrets.X }} placeholder is fine — it resolves at run time
    and falls through to the .env layers when the secret does not exist.
    """
    envs = load_pipeline(name)["environment"]["envs"]

    for field in ("OPENAI_API_KEY", "GITHUB_TOKEN", "API_KEY", "GRADIO_PASSWORD"):
        value = envs[field].strip()
        assert value == "" or value.startswith("${{"), (
            f"{name}: {field} looks like a real credential"
        )


def test_both_yamls_describe_the_same_pipeline():
    """The two files differ only in how configuration is supplied.

    fasttrack_pipeline_inline.yaml is generated by copying everything from
    `params:` down, so a change to the DAG in one and not the other means the
    generation step was skipped.
    """
    base, inline = (load_pipeline(name) for name in PIPELINE_YAMLS)

    def without_envs(tasks):
        """Drop only environment.envs: that is the one thing the files differ in.

        The base file leaves each task's envs empty and supplies configuration
        once; the inline file repeats a populated block on every task, because
        FastTrack does not reliably propagate the pipeline-level one.
        """
        stripped = []
        for task in tasks:
            task = {k: v for k, v in task.items()}
            task["environment"] = {
                k: v for k, v in task["environment"].items() if k != "envs"
            }
            stripped.append(task)
        return stripped

    assert without_envs(base["tasks"]) == without_envs(inline["tasks"])
    assert base["version"] == inline["version"]
    assert base["ownership"] == inline["ownership"]


def test_the_dag_is_wired_head_to_services():
    """One head, a linear ingest chain, and both services fed by staging."""
    tasks = {t["name"]: t for t in load_pipeline(PIPELINE_YAMLS[0])["tasks"]}

    heads = [n for n, t in tasks.items() if not t.get("dependencies")]
    assert heads == ["fetch-code"], "exactly one node may declare no dependency"

    # FastTrack task names must stay short.
    assert all(len(n) < 20 for n in tasks), [n for n in tasks if len(n) >= 20]

    for service in ("serve-fastapi", "serve-gradio"):
        assert tasks[service]["dependencies"] == ["stage-service"]
        assert tasks[service]["type"] == "deployment"
        # Model storage is the only mount a serving container shares with the
        # batch tasks; naming a vFolder here is what breaks portability.
        assert "mounts" not in tasks[service]
        assert tasks[service]["service"]["model"] == PLACEHOLDER_VFOLDER
        assert len(tasks[service]["service"]["name"]) <= 24


@pytest.mark.parametrize("name", PIPELINE_YAMLS)
def test_only_stage_service_mounts_a_vfolder(name):
    """One mount, on one task, and named as a placeholder.

    A deployment resolves model_definition_path against its own model mount, so
    the definitions have to be written into that vFolder and stage-service has
    to mount it. That is the single account-scoped value in either file — every
    other task still runs without naming one, which is what keeps the pipeline
    shareable.
    """
    mounted = {
        task["name"]: task["mounts"]
        for task in load_pipeline(name)["tasks"]
        if task.get("mounts")
    }
    assert list(mounted) == ["stage-service"], f"{name}: unexpected mounts {mounted}"
    assert mounted["stage-service"] == [PLACEHOLDER_VFOLDER], (
        f"{name}: mount should stay a placeholder, got {mounted['stage-service']}"
    )


# --- sources.yaml ---------------------------------------------------------


def test_shipped_sources_are_valid_and_each_declares_a_canary():
    cfg = SourcesConfig.load(SOURCES_YAML)
    assert cfg.names() == ["backendai", "webui", "mlxcel", "all-smi", "bssh"]
    for spec in cfg.sources:
        assert spec.include, f"{spec.name} selects no files"
        assert spec.verify_query, f"{spec.name} has no verify_query"


def test_globs_select_recursively_and_exclusions_are_subtracted(tmp_path):
    (tmp_path / "docs" / "nested").mkdir(parents=True)
    (tmp_path / "docs" / "locales").mkdir()
    (tmp_path / "docs" / "top.rst").write_text("x")
    (tmp_path / "docs" / "nested" / "deep.rst").write_text("x")
    (tmp_path / "docs" / "locales" / "ko.rst").write_text("x")
    (tmp_path / "README.md").write_text("x")

    spec = SourceSpec(
        name="t",
        url="https://example.invalid/t.git",
        include=["docs/**/*.rst", "README.md"],
        exclude=["docs/locales/**/*"],
    )
    selected = [p.relative_to(tmp_path).as_posix() for p in spec.select_files(tmp_path)]

    # `docs/**/*.rst` must match the top-level file as well as the nested one.
    assert selected == ["README.md", "docs/nested/deep.rst", "docs/top.rst"]


def test_a_symlink_escaping_the_repo_is_refused(tmp_path):
    """Reproduces the exfiltration path: a source repo symlinks out to a secret.

    `Path.glob` returns symlinks and `is_file()` follows them, so the converter
    would read *through* the link and copy the target's contents into the
    corpus, where they get embedded and answered from. The ingestion container
    has the operator's model storage mounted at /models — the documented home
    of their .env — and the source repos are third-party by design.
    """
    secret = tmp_path / "models" / ".env"
    secret.parent.mkdir()
    secret.write_text("OPENAI_API_KEY=sk-should-never-be-indexed\n")

    repo = tmp_path / "repo"
    (repo / "docs").mkdir(parents=True)
    (repo / "docs" / "real.md").write_text("genuine documentation")
    (repo / "docs" / "faq.md").symlink_to(secret)             # absolute escape
    (repo / "docs" / "sneaky.md").symlink_to("../../models/.env")  # relative escape
    (repo / "README.md").symlink_to(secret)                   # literal-pattern escape

    spec = SourceSpec(
        name="t", url="u", include=["docs/**/*.md", "README.md"]
    )
    selected = spec.select_files(repo)

    assert [p.name for p in selected] == ["real.md"]
    # Belt and braces: nothing selected reads back as the secret.
    assert all("sk-should-never-be-indexed" not in p.read_text() for p in selected)


def test_a_symlink_staying_inside_the_repo_is_kept(tmp_path):
    """Only escaping links are a problem; in-repo links are ordinary docs."""
    repo = tmp_path / "repo"
    (repo / "docs").mkdir(parents=True)
    (repo / "docs" / "canonical.md").write_text("the real page")
    (repo / "docs" / "alias.md").symlink_to(repo / "docs" / "canonical.md")

    selected = SourceSpec(name="t", url="u", include=["docs/**/*.md"]).select_files(repo)

    assert [p.name for p in selected] == ["alias.md", "canonical.md"]


def test_a_broken_symlink_is_refused_rather_than_raising(tmp_path):
    repo = tmp_path / "repo"
    (repo / "docs").mkdir(parents=True)
    (repo / "docs" / "dangling.md").symlink_to(tmp_path / "gone.md")

    assert SourceSpec(name="t", url="u", include=["docs/**/*.md"]).select_files(repo) == []


def test_root_level_includes_work(tmp_path):
    """all-smi keeps its real documentation at the repo root, not in docs/."""
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "PR61_REVIEW.md").write_text("dev log")
    (tmp_path / "API.md").write_text("x")

    spec = SourceSpec(name="t", url="u", include=["API.md"])
    selected = [p.name for p in spec.select_files(tmp_path)]
    assert selected == ["API.md"]


# --- path resolution ------------------------------------------------------


def test_output_root_priority(monkeypatch, tmp_path):
    monkeypatch.delenv("PIPELINE_OUTPUT_ROOT", raising=False)
    monkeypatch.delenv("PIPELINE_DATA_ROOT", raising=False)
    assert resolve_output_root() == DEFAULT_DATA_ROOT.resolve()

    monkeypatch.setenv("PIPELINE_DATA_ROOT", str(tmp_path / "data"))
    assert resolve_output_root() == (tmp_path / "data").resolve()

    # The per-task FastTrack mount outranks the single-root fallback.
    monkeypatch.setenv("PIPELINE_OUTPUT_ROOT", str(tmp_path / "outputs"))
    assert resolve_output_root() == (tmp_path / "outputs").resolve()

    # An explicit CLI value outranks everything.
    assert resolve_output_root(str(tmp_path / "cli")) == (tmp_path / "cli").resolve()


def test_input_root_is_none_when_unset(monkeypatch):
    monkeypatch.delenv("PIPELINE_INPUT_ROOT", raising=False)
    assert resolve_input_root() is None


# --- seeding --------------------------------------------------------------


def _stage(root: Path, stage: str, filename: str = "f.txt") -> None:
    (root / stage).mkdir(parents=True, exist_ok=True)
    (root / stage / filename).write_text("x")


def test_head_node_seeds_nothing_because_it_has_no_input_mount(tmp_path):
    """Head-ness is structural: no dependency means no /pipeline/input1.

    Gating this on a job-index value instead is what broke a production run —
    a cluster reported index 1 for a mid-chain task, every node then skipped
    seeding, and the chain died on an empty upstream stage.
    """
    output = tmp_path / "outputs"
    assert seed_from_input(output, None) == []
    assert seed_from_input(output, tmp_path / "never-mounted") == []


def test_the_head_node_declares_that_it_consumes_nothing(tmp_path):
    """`seed_stages=()` is the head's own claim, not a bet on the scheduler.

    Relying only on "FastTrack mounts the head no input1" leaves the head
    copying the tree forward if a stale or empty mount ever does appear.
    """
    inp, out = tmp_path / "in", tmp_path / "out"
    for stage in ("01_repos", "03_indices"):
        _stage(inp, stage)

    assert seed_from_input(out, inp, stages=()) == []
    assert not (out / "01_repos").exists()
    assert not (out / "03_indices").exists()


def test_the_head_task_script_actually_passes_that_declaration():
    """The guarantee above is worthless if node 01 forgets to declare it."""
    source = (PROJECT_ROOT / "pipeline" / "tasks" / "01_clone_sources.py").read_text()
    assert 'run_task("01_clone_sources", handler, seed_stages=())' in source


def test_local_single_root_run_does_not_copy_onto_itself(tmp_path):
    _stage(tmp_path, "01_repos")
    assert seed_from_input(tmp_path, tmp_path) == []


def test_seed_stages_narrows_what_is_carried_forward(tmp_path):
    """Without narrowing, every node drags the repos and markdown along.

    That is tens of gigabytes of output-mount I/O per run for data nothing
    downstream reads.
    """
    inp, out = tmp_path / "in", tmp_path / "out"
    for stage in ("01_repos", "02_docs_md", "03_indices", "99_state"):
        _stage(inp, stage)

    seeded = seed_from_input(out, inp, stages=("03_indices", "99_state"))

    assert seeded == ["03_indices", "99_state"]
    assert not (out / "01_repos").exists()
    assert (out / "03_indices" / "f.txt").exists()


def _run_task_capturing(tmp_path, monkeypatch, caplog, *, seed_stages, on_fasttrack: bool):
    """Drive run_task with a no-op handler and return the captured log records."""
    import logging

    from pipeline.runner import run_task

    output = tmp_path / "outputs"
    monkeypatch.setenv("PIPELINE_OUTPUT_ROOT", str(output))
    monkeypatch.setenv("PIPELINE_INPUT_ROOT", str(tmp_path / "never-mounted"))
    if on_fasttrack:
        monkeypatch.setenv("BACKENDAI_PIPELINE_JOB_INDEX", "3")
    else:
        monkeypatch.delenv("BACKENDAI_PIPELINE_JOB_INDEX", raising=False)
    monkeypatch.setattr(
        "sys.argv", ["t", "--project", "all", "--sources", str(SOURCES_YAML)]
    )

    with caplog.at_level(logging.WARNING):
        run_task("t", lambda args, cfg, root: {}, seed_stages=seed_stages)
    return caplog.text


def test_a_broken_chain_warns_before_it_fails(tmp_path, monkeypatch, caplog):
    """A node that needs upstream stages and got none should say so.

    Otherwise the first symptom is an empty-directory error several frames
    deeper, which reads like a bug in this node rather than a broken edge.
    """
    text = _run_task_capturing(
        tmp_path, monkeypatch, caplog, seed_stages=("03_indices",), on_fasttrack=True
    )
    assert "nothing seeded" in text


def test_the_head_node_is_silent_even_though_it_seeds_nothing(tmp_path, monkeypatch, caplog):
    """`seed_stages=()` means "consumes nothing", so an empty seed is correct."""
    import logging

    from pipeline.runner import run_task

    monkeypatch.setenv("PIPELINE_OUTPUT_ROOT", str(tmp_path / "outputs"))
    monkeypatch.setenv("PIPELINE_INPUT_ROOT", str(tmp_path / "never-mounted"))
    monkeypatch.setenv("BACKENDAI_PIPELINE_JOB_INDEX", "1")
    monkeypatch.setattr(
        "sys.argv", ["t", "--project", "all", "--sources", str(SOURCES_YAML)]
    )

    with caplog.at_level(logging.WARNING):
        run_task("t", lambda args, cfg, root: {}, seed_stages=())

    assert "nothing seeded" not in caplog.text


def test_a_local_run_is_silent_because_it_has_no_input_mount(tmp_path, monkeypatch, caplog):
    """Locally there is no chain to break, so the warning would be pure noise."""
    text = _run_task_capturing(
        tmp_path, monkeypatch, caplog, seed_stages=("03_indices",), on_fasttrack=False
    )
    assert "nothing seeded" not in text


def test_seeding_merges_so_this_task_can_overwrite_its_own_stage(tmp_path):
    inp, out = tmp_path / "in", tmp_path / "out"
    _stage(inp, "03_indices", "from_upstream.txt")
    _stage(out, "03_indices", "already_here.txt")

    seed_from_input(out, inp)

    assert (out / "03_indices" / "from_upstream.txt").exists()
    assert (out / "03_indices" / "already_here.txt").exists()
