# Dataset Configuration for Preprocessing
# 이 파일은 데이터셋 전처리 시 사용할 컬럼 매핑과 메시지 포맷을 정의합니다.

# Training용 컬럼 매핑 (key: messages_format에서 사용할 변수명, value: 실제 데이터셋 컬럼명)
training_columns:
  question: "Open-ended Verifiable Question"
  cot: "Complex_CoT" 
  response: "Response"

# Training용 messages 포맷 템플릿
messages_format:
  system_prompt: |
    Below is an instruction that describes a task, paired with an input that provides further context. 
    Write a response that appropriately completes the request. 
    Before answering, think carefully about the question and create a step-by-step chain of thoughts to ensure a logical and accurate response.
  
  # messages 구조 정의 (role과 content로 구성)
  messages:
    - role: "system"
      content: "{system_prompt}"
    - role: "user" 
      content: "{question}"
    - role: "assistant"
      content: "<think>\n{cot}\n</think>\n{response}"

# Evaluation용 컬럼 매핑
evaluate_columns:
  query: "Open-ended Verifiable Question"
  response: "Response"

# 데이터 품질 필터링 설정
data_filtering:
  # 필수 체크할 컬럼들 (None 값과 빈 문자열 체크)
  required_columns:
    - "Open-ended Verifiable Question"
    - "Complex_CoT"
    - "Response"
  
  # 최소 텍스트 길이
  min_text_length: 1
